const fs = require('fs');

const enTsPath = 'src/dictionaries/en.ts';
const esTsPath = 'src/dictionaries/es.ts';

let enTs = fs.readFileSync(enTsPath, 'utf8');
let esTs = fs.readFileSync(esTsPath, 'utf8');

const enBuildTeams = `
  buildTeams: {
    heroTitle: "Build the team you need without hiring friction, legal complexity or unnecessary overhead.",
    heroDesc1: "Core helps U.S. companies recruit, hire, staff and manage qualified talent across Latin America and global markets through flexible talent solutions.",
    heroDesc2: "Whether you need long-term employees, temporary support, project-based talent, staff augmentation, legal hiring structures abroad or employment visa support, we help you find the right way to build your team.",
    bestFitTitle: "Best fit for companies that need to:",
    bestFit1: "Hire qualified talent beyond the U.S. market.",
    bestFit2: "Reduce hiring costs without compromising quality.",
    bestFit3: "Build remote or nearshore teams.",
    bestFit4: "Cover temporary, project-based or long-term roles.",
    bestFit5: "Hire without opening a local entity.",
    bestFit6: "Simplify legal, administrative and hiring complexity.",
    startBuildingBtn: "START BUILDING YOUR TEAM",
    transitionTitle: "Hiring should help you grow, not slow you down.",
    transitionP1: "For many growing companies, building a team comes with too much complexity: high hiring costs in the U.S., long recruitment cycles, legal uncertainty, local entity requirements, payroll questions, onboarding work and operational burden.",
    transitionP2: "Core simplifies that process. We help you access qualified talent beyond the U.S. market and structure the right hiring solution based on what your business actually needs: a permanent hire, temporary coverage, specialized support, a remote team, or a compliant way to hire abroad.",
    transitionP3: "You focus on growth. We help you build the team to support it.",
    useCasesTitle: "What are you trying to solve?",
    useCasesDesc: "You may not know which hiring model you need yet. That is why we start with the business problem, then match it with the right talent solution.",
    uc1Title: "Hire abroad without opening a local entity",
    uc1P1: "You found the right talent in another country, but you do not want to create a local company, manage legal setup or figure out employment compliance alone.",
    uc1P2: "Core helps you legally hire talent abroad through the right structure, including Employer of Record solutions when needed",
    servicesMayInclude: "Services that may include:",
    uc1S1: "Employer of Record",
    uc1S2: "Hiring setup",
    uc1S3: "Onboarding support",
    uc1S4: "Compliance support",
    uc1S5: "Ongoing management",
    uc2Title: "Build a long-term team outside the U.S.",
    uc2P1: "Hiring only in the U.S. can be expensive and slow. Core helps you find qualified talent in Latin America and other global markets where hiring can be more cost-efficient without sacrificing quality or productivity.",
    uc2S1: "Recruitment & Selection",
    uc2S2: "Employer of Record",
    uc2S3: "Hiring support",
    uc2S4: "Onboarding support",
    uc2S5: "Talent management",
    uc3Title: "Cover temporary or project-based roles",
    uc3P1: "Sometimes you do not need a permanent hire. You need reliable talent for a specific project, season, workload increase or temporary need.",
    uc3P2: "Core helps you cover those roles with flexible staffing solutions that give you capacity without unnecessary long-term commitments.",
    uc3S1: "Staffing",
    uc3S2: "Temporary hiring",
    uc3S3: "Project-based talent",
    uc3S4: "Hiring and onboarding support",
    uc3S5: "Ongoing coordination",
    uc4Title: "Strengthen your existing team with specialized talent",
    uc4P1: "Your team may already be in place, but needs more capacity or specific skills to move faster. Core helps you add qualified professionals who can support your existing team without adding internal hiring burden.",
    uc4S1: "Staff Augmentation",
    uc4S2: "Specialized recruitment",
    uc4S3: "Staffing",
    uc4S4: "Remote talent support",
    uc4S5: "Ongoing coordination",
    uc5Title: "Manage employment visa needs in Mexico",
    uc5P1: "If your company needs to bring foreign employees to Mexico or manage employment-related immigration processes, Core can support the visa process with practical guidance and administrative coordination.",
    uc5S1: "Employment Visa Services",
    uc5S2: "Documentation support",
    uc5S3: "Process coordination",
    uc5S4: "Administrative guidance",
    uc5S5: "Mexico-based hiring support",
    bottomTitle: "Talent solutions designed around how you need to hire.",
    card1: "Recruitment & Selection",
    card2: "Staffing",
    card3: "Employer of Record (EOR)",
    card4: "Staff Augmentation",
    card5: "Employment Visa Services",
    card6: "Hiring, onboarding and ongoing support"
  },`;

const enRunOperations = `
  runOperations: {
    heroTitle: "Run your operations without hiring more people or losing control.",
    heroDesc1: "Core helps U.S. companies outsource administrative, finance, bookkeeping, payroll, contractor payment and back-office operations through structured BPO support.",
    heroDesc2: "We help growing companies reduce operational workload, organize critical processes and give owners and teams more time to focus on sales, clients and growth.",
    bestFitTitle: "Best fit for companies that need to:",
    bestFit1: "Free up time from administrative work.",
    bestFit2: "Reduce operational costs without losing control.",
    bestFit3: "Organize bookkeeping, payroll and finance processes.",
    bestFit4: "Pay contractors consistently and compliantly.",
    bestFit5: "Keep back-office tasks running month after month.",
    bestFit6: "Allow owners and teams to focus on sales, clients and growth.",
    startBuildingBtn: "START BUILDING YOUR TEAM",
    transitionTitle: "Your business should not depend on you doing everything.",
    transitionP1: "As companies grow, operational work starts to pile up. Bookkeeping, payroll, contractor payments, administrative tasks, reporting, follow-ups and back-office processes become harder to manage internally.",
    transitionP2: "At some point, the problem is not only lack of time. It is lack of structure.",
    transitionP3: "Core helps U.S. companies delegate the operational work that keeps the business running, without building a full internal team or losing visibility over the process. Through CoreBooks and BPO support, we help your operation stay organized, up to date and compliant.",
    transitionP4: "You focus on growing the business. We help keep the operation moving.",
    useCasesTitle: "What operational challenge are you trying to solve?",
    useCasesDesc: "You may not need a full internal department. You may need the right operational support behind the business. Core starts with the problem, then connects it with the right outsourced solution.",
    uc1Title: "Get control of your back office",
    uc1P1: "Your business is growing, but admin tasks, documents, follow-ups and internal processes are scattered. Things get done, but not always with the structure or consistency you need.",
    uc1P2: "Core helps organize and run back-office tasks so your business can operate with more clarity, control and continuity.",
    servicesMayInclude: "Services that may include:",
    uc1S1: "Back-Office Support",
    uc1S2: "Administrative Support",
    uc1S3: "Operational process support",
    uc1S4: "Document coordination",
    uc1S5: "Ongoing task management",
    uc2Title: "Fix your financial operations",
    uc2P1: "If bookkeeping, reconciliations, financial records or reporting are delayed or inconsistent, it becomes harder to make decisions and understand how the business is really performing.",
    uc2P2: "CoreBooks helps keep your financial operations organized, updated and easier to manage month after month.",
    uc2S1: "Bookkeeping",
    uc2S2: "Finance Support",
    uc2S3: "Reporting support",
    uc2S4: "Account reconciliation support",
    uc2S5: "Administrative finance tasks",
    uc3Title: "Delegate payroll and contractor payments",
    uc3P1: "Paying employees, contractors or remote teams can become time-consuming and sensitive. Mistakes, delays or lack of structure can create unnecessary risk and frustration.",
    uc3P2: "Core helps manage payroll and contractor payment processes with consistency, control and compliance-minded execution.",
    uc3S1: "Payroll Services",
    uc3S2: "Contractor Payments",
    uc3S3: "Payment coordination",
    uc3S4: "Administrative support",
    uc3S5: "Compliance-minded process support",
    uc4Title: "Reduce operational workload",
    uc4P1: "When owners or internal teams spend too much time on administrative work, the business loses focus. Sales, client service and growth initiatives get pushed aside.",
    uc4P2: "Core helps take recurring operational tasks off your team's plate, giving them more time to focus on higher-value work.",
    uc4S1: "Administrative Support",
    uc4S2: "BPO Support",
    uc4S3: "Back-Office Support",
    uc4S4: "Finance Support",
    uc4S5: "Recurring task management",
    uc5Title: "Scale operations without building a full internal team",
    uc5P1: "Your company may need more operational capacity, but not necessarily a full finance, admin, payroll or back-office department in the U.S.",
    uc5P2: "Core helps you build an outsourced operations structure that supports growth without increasing internal complexity or fixed overhead.",
    uc5S1: "BPO / Back-Office Support",
    uc5S2: "Bookkeeping",
    uc5S3: "Payroll Services",
    uc5S4: "Contractor Payments",
    uc5S5: "Administrative Support",
    uc5S6: "Finance Support",
    bottomTitle: "Outsourced operations designed to keep your business organized and moving.",
    card1: "Bookkeeping",
    card2: "Payroll Services",
    card3: "Contractor Payments",
    card4: "BPO / Back-Office Support",
    card5: "Administrative Support",
    card6: "Finance Support"
  }`;

const esBuildTeams = `
  buildTeams: {
    heroTitle: "Construye el equipo que necesitas sin fricciones de contratación, complejidad legal ni costos innecesarios.",
    heroDesc1: "Core ayuda a las empresas de EE. UU. a reclutar, contratar y gestionar talento calificado en América Latina y mercados globales mediante soluciones de talento flexibles.",
    heroDesc2: "Ya sea que necesites empleados a largo plazo, apoyo temporal, talento por proyectos, staff augmentation, estructuras legales de contratación en el extranjero o apoyo con visas de trabajo, te ayudamos a encontrar la manera correcta de armar tu equipo.",
    bestFitTitle: "Ideal para empresas que necesitan:",
    bestFit1: "Contratar talento calificado más allá del mercado de EE. UU.",
    bestFit2: "Reducir costos de contratación sin comprometer la calidad.",
    bestFit3: "Construir equipos remotos o nearshore.",
    bestFit4: "Cubrir roles temporales, basados en proyectos o a largo plazo.",
    bestFit5: "Contratar sin abrir una entidad local.",
    bestFit6: "Simplificar la complejidad legal, administrativa y de contratación.",
    startBuildingBtn: "EMPIEZA A ARMAR TU EQUIPO",
    transitionTitle: "Contratar debería ayudarte a crecer, no retrasarte.",
    transitionP1: "Para muchas empresas en crecimiento, armar un equipo conlleva demasiada complejidad: altos costos de contratación en EE. UU., ciclos largos de reclutamiento, incertidumbre legal, requisitos de entidad local, preguntas sobre nómina, trabajo de onboarding y carga operativa.",
    transitionP2: "Core simplifica ese proceso. Te ayudamos a acceder a talento calificado más allá del mercado de EE. UU. y a estructurar la solución de contratación adecuada según lo que tu negocio realmente necesita: una contratación permanente, cobertura temporal, apoyo especializado, un equipo remoto, o una forma legal de contratar en el extranjero.",
    transitionP3: "Tú te enfocas en el crecimiento. Nosotros te ayudamos a construir el equipo para respaldarlo.",
    useCasesTitle: "¿Qué estás intentando resolver?",
    useCasesDesc: "Puede que aún no sepas qué modelo de contratación necesitas. Por eso empezamos con el problema de negocio y luego lo conectamos con la solución de talento adecuada.",
    uc1Title: "Contratar en el extranjero sin abrir una entidad local",
    uc1P1: "Encontraste el talento adecuado en otro país, pero no quieres crear una empresa local, gestionar la configuración legal o descifrar el cumplimiento laboral por tu cuenta.",
    uc1P2: "Core te ayuda a contratar talento legalmente en el extranjero a través de la estructura adecuada, incluyendo soluciones de Employer of Record (EOR) cuando sea necesario.",
    servicesMayInclude: "Servicios que pueden incluir:",
    uc1S1: "Employer of Record (EOR)",
    uc1S2: "Configuración de contratación",
    uc1S3: "Apoyo en onboarding",
    uc1S4: "Apoyo en cumplimiento normativo",
    uc1S5: "Gestión continua",
    uc2Title: "Construir un equipo a largo plazo fuera de EE. UU.",
    uc2P1: "Contratar solo en EE. UU. puede ser costoso y lento. Core te ayuda a encontrar talento calificado en América Latina y otros mercados globales donde la contratación puede ser más rentable sin sacrificar calidad o productividad.",
    uc2S1: "Reclutamiento y Selección",
    uc2S2: "Employer of Record (EOR)",
    uc2S3: "Apoyo en contratación",
    uc2S4: "Apoyo en onboarding",
    uc2S5: "Gestión de talento",
    uc3Title: "Cubrir roles temporales o por proyecto",
    uc3P1: "A veces no necesitas una contratación permanente. Necesitas talento confiable para un proyecto específico, temporada, aumento de carga de trabajo o necesidad temporal.",
    uc3P2: "Core te ayuda a cubrir esos roles con soluciones de staffing flexibles que te brindan capacidad sin compromisos innecesarios a largo plazo.",
    uc3S1: "Staffing",
    uc3S2: "Contratación temporal",
    uc3S3: "Talento por proyecto",
    uc3S4: "Apoyo en contratación y onboarding",
    uc3S5: "Coordinación continua",
    uc4Title: "Fortalecer tu equipo existente con talento especializado",
    uc4P1: "Puede que tu equipo ya esté formado, pero necesite más capacidad o habilidades específicas para avanzar más rápido. Core te ayuda a agregar profesionales calificados que puedan apoyar a tu equipo existente sin agregar carga de contratación interna.",
    uc4S1: "Staff Augmentation",
    uc4S2: "Reclutamiento especializado",
    uc4S3: "Staffing",
    uc4S4: "Apoyo de talento remoto",
    uc4S5: "Coordinación continua",
    uc5Title: "Gestionar necesidades de visas de trabajo en México",
    uc5P1: "Si tu empresa necesita traer empleados extranjeros a México o gestionar procesos de inmigración relacionados con el empleo, Core puede apoyar el proceso de visas con orientación práctica y coordinación administrativa.",
    uc5S1: "Servicios de Visa de Empleo",
    uc5S2: "Apoyo con documentación",
    uc5S3: "Coordinación del proceso",
    uc5S4: "Orientación administrativa",
    uc5S5: "Apoyo en contratación con sede en México",
    bottomTitle: "Soluciones de talento diseñadas según tu necesidad de contratación.",
    card1: "Reclutamiento y Selección",
    card2: "Staffing",
    card3: "Employer of Record (EOR)",
    card4: "Staff Augmentation",
    card5: "Servicios de Visa de Empleo",
    card6: "Contratación, onboarding y gestión continua"
  },`;

const esRunOperations = `
  runOperations: {
    heroTitle: "Opera tu negocio sin contratar más personas ni perder el control.",
    heroDesc1: "Core ayuda a las empresas de EE. UU. a externalizar operaciones administrativas, contabilidad, nómina, pago a contratistas y back-office a través de soporte BPO estructurado.",
    heroDesc2: "Ayudamos a empresas en crecimiento a reducir la carga operativa, organizar procesos críticos y darles a los dueños y equipos más tiempo para enfocarse en ventas, clientes y crecimiento.",
    bestFitTitle: "Ideal para empresas que necesitan:",
    bestFit1: "Liberar tiempo del trabajo administrativo.",
    bestFit2: "Reducir costos operativos sin perder el control.",
    bestFit3: "Organizar procesos de contabilidad, nómina y finanzas.",
    bestFit4: "Pagar a contratistas de manera constante y en cumplimiento.",
    bestFit5: "Mantener las tareas de back-office funcionando mes a mes.",
    bestFit6: "Permitir que dueños y equipos se enfoquen en ventas y crecimiento.",
    startBuildingBtn: "EMPIEZA A ARMAR TU EQUIPO",
    transitionTitle: "Tu negocio no debería depender de que tú hagas todo.",
    transitionP1: "A medida que las empresas crecen, el trabajo operativo empieza a acumularse. La contabilidad, nómina, pagos a contratistas, tareas administrativas, informes, seguimientos y procesos de back-office se vuelven más difíciles de gestionar internamente.",
    transitionP2: "Llega un punto donde el problema no es solo la falta de tiempo. Es la falta de estructura.",
    transitionP3: "Core ayuda a las empresas de EE. UU. a delegar el trabajo operativo que mantiene el negocio funcionando, sin tener que construir un equipo interno completo ni perder visibilidad sobre el proceso. A través de CoreBooks y soporte BPO, ayudamos a que tu operación se mantenga organizada, actualizada y en cumplimiento.",
    transitionP4: "Tú te enfocas en hacer crecer el negocio. Nosotros ayudamos a mantener la operación en marcha.",
    useCasesTitle: "¿Qué desafío operativo intentas resolver?",
    useCasesDesc: "Puede que no necesites un departamento interno completo. Puedes necesitar el soporte operativo adecuado detrás del negocio. Core empieza con el problema, luego lo conecta con la solución externalizada correcta.",
    uc1Title: "Toma el control de tu back-office",
    uc1P1: "Tu negocio está creciendo, pero las tareas administrativas, documentos, seguimientos y procesos internos están dispersos. Las cosas se hacen, pero no siempre con la estructura o consistencia que necesitas.",
    uc1P2: "Core ayuda a organizar y ejecutar tareas de back-office para que tu negocio pueda operar con más claridad, control y continuidad.",
    servicesMayInclude: "Servicios que pueden incluir:",
    uc1S1: "Soporte Back-Office",
    uc1S2: "Soporte Administrativo",
    uc1S3: "Soporte de procesos operativos",
    uc1S4: "Coordinación de documentos",
    uc1S5: "Gestión continua de tareas",
    uc2Title: "Arregla tus operaciones financieras",
    uc2P1: "Si la contabilidad, conciliaciones, registros financieros o reportes están retrasados o son inconsistentes, se vuelve más difícil tomar decisiones y entender cómo le está yendo realmente al negocio.",
    uc2P2: "CoreBooks ayuda a mantener tus operaciones financieras organizadas, actualizadas y más fáciles de manejar mes tras mes.",
    uc2S1: "Contabilidad (Bookkeeping)",
    uc2S2: "Soporte Financiero",
    uc2S3: "Soporte en generación de reportes",
    uc2S4: "Soporte en conciliación de cuentas",
    uc2S5: "Tareas administrativas financieras",
    uc3Title: "Delega la nómina y pagos a contratistas",
    uc3P1: "Pagar a empleados, contratistas o equipos remotos puede consumir mucho tiempo y ser delicado. Los errores, retrasos o la falta de estructura pueden crear riesgos y frustraciones innecesarias.",
    uc3P2: "Core ayuda a gestionar los procesos de nómina y pago a contratistas con consistencia, control y una ejecución enfocada en el cumplimiento normativo.",
    uc3S1: "Servicios de Nómina",
    uc3S2: "Pagos a Contratistas",
    uc3S3: "Coordinación de pagos",
    uc3S4: "Soporte Administrativo",
    uc3S5: "Soporte de procesos en cumplimiento",
    uc4Title: "Reduce la carga operativa",
    uc4P1: "Cuando los dueños o equipos internos pasan demasiado tiempo en trabajo administrativo, el negocio pierde enfoque. Las ventas, el servicio al cliente y las iniciativas de crecimiento quedan en un segundo plano.",
    uc4P2: "Core ayuda a quitar tareas operativas recurrentes del plato de tu equipo, dándoles más tiempo para enfocarse en trabajo de mayor valor.",
    uc4S1: "Soporte Administrativo",
    uc4S2: "Soporte BPO",
    uc4S3: "Soporte Back-Office",
    uc4S4: "Soporte Financiero",
    uc4S5: "Gestión de tareas recurrentes",
    uc5Title: "Escala operaciones sin construir un equipo interno completo",
    uc5P1: "Tu empresa puede necesitar más capacidad operativa, pero no necesariamente un departamento completo de finanzas, administración, nómina o back-office en EE. UU.",
    uc5P2: "Core te ayuda a construir una estructura de operaciones externalizada que respalda el crecimiento sin aumentar la complejidad interna o los costos fijos.",
    uc5S1: "BPO / Soporte Back-Office",
    uc5S2: "Contabilidad (Bookkeeping)",
    uc5S3: "Servicios de Nómina",
    uc5S4: "Pagos a Contratistas",
    uc5S5: "Soporte Administrativo",
    uc5S6: "Soporte Financiero",
    bottomTitle: "Operaciones externalizadas diseñadas para mantener tu negocio organizado y en marcha.",
    card1: "Contabilidad (Bookkeeping)",
    card2: "Servicios de Nómina",
    card3: "Pagos a Contratistas",
    card4: "BPO / Soporte Back-Office",
    card5: "Soporte Administrativo",
    card6: "Soporte Financiero"
  }`;

if (!enTs.includes('buildTeams: {')) {
  enTs = enTs.replace('home: {', enBuildTeams + '\\n' + enRunOperations + ',\\n  home: {');
  fs.writeFileSync(enTsPath, enTs);
}

if (!esTs.includes('buildTeams: {')) {
  esTs = esTs.replace('home: {', esBuildTeams + '\\n' + esRunOperations + ',\\n  home: {');
  fs.writeFileSync(esTsPath, esTs);
}

console.log('Dictionaries updated!');
