import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Navbar from '../components/Navbar';
import Footer from '../components/Footer';

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <head>
        <script src="https://cdn.tailwindcss.com?plugins=forms,container-queries"></script>
        <link href="https://fonts.googleapis.com/css2?family=Hanken+Grotesk:wght@400;700;800&family=Inter:wght@400;600&family=Montserrat:wght@700&family=Open+Sans:wght@400;700&display=swap" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:wght,FILL@100..700,0..1&display=swap" rel="stylesheet" />
        <script
          id="tailwind-config"
          dangerouslySetInnerHTML={{
            __html: `
              tailwind.config = {
                  darkMode: "class",
                  theme: {
                      extend: {
                          "colors": {
                              "surface-variant": "#dae2fd",
                              "error": "#ba1a1a",
                              "secondary-fixed": "#d3e5f1",
                              "secondary": "#50616b",
                              "on-background": "#131b2e",
                              "on-primary-fixed": "#1c0062",
                              "tertiary-container": "#80707a",
                              "tertiary-fixed": "#f1dde9",
                              "surface-tint": "#603ce2",
                              "primary-container": "#7757fa",
                              "surface-container-highest": "#dae2fd",
                              "surface": "#faf8ff",
                              "surface-dim": "#d2d9f4",
                              "surface-container-low": "#f2f3ff",
                              "on-secondary-container": "#566771",
                              "secondary-fixed-dim": "#b7c9d5",
                              "outline": "#797587",
                              "secondary-container": "#d3e5f1",
                              "on-tertiary": "#ffffff",
                              "on-surface-variant": "#484555",
                              "primary-fixed": "#e6deff",
                              "on-tertiary-fixed-variant": "#51434c",
                              "primary-fixed-dim": "#cabeff",
                              "surface-container-high": "#e2e7ff",
                              "on-tertiary-container": "#fffbff",
                              "on-error": "#ffffff",
                              "surface-bright": "#faf8ff",
                              "primary": "#6C34E0",
                              "on-primary-fixed-variant": "#4816cb",
                              "on-secondary-fixed": "#0c1e26",
                              "background": "#faf8ff",
                              "on-error-container": "#93000a",
                              "surface-container-lowest": "#ffffff",
                              "inverse-on-surface": "#eef0ff",
                              "on-surface": "#131b2e",
                              "tertiary": "#675862",
                              "error-container": "#ffdad6",
                              "inverse-primary": "#cabeff",
                              "tertiary-fixed-dim": "#d5c1cd",
                              "on-primary-container": "#fffbff",
                              "on-primary": "#ffffff",
                              "on-tertiary-fixed": "#231820",
                              "surface-container": "#eaedff",
                              "inverse-surface": "#283044",
                              "on-secondary-fixed-variant": "#384953",
                              "outline-variant": "#c9c4d8",
                              "on-secondary": "#ffffff"
                          },
                          "borderRadius": {
                              "DEFAULT": "0.25rem",
                              "lg": "0.5rem",
                              "xl": "0.75rem",
                              "full": "9999px"
                          },
                          "spacing": {
                              "section-gap": "120px",
                              "margin-mobile": "16px",
                              "gutter": "24px",
                              "base": "4px",
                              "margin-desktop": "80px"
                          },
                          "fontFamily": {
                              "headline-lg": ["Hanken Grotesk"],
                              "display-lg-mobile": ["Hanken Grotesk"],
                              "display-lg": ["Hanken Grotesk"],
                              "headline-md": ["Hanken Grotesk"],
                              "body-md": ["Inter"],
                              "body-lg": ["Inter"],
                              "label-bold": ["Inter"],
                              "montserrat": ["Montserrat"],
                              "open-sans": ["Open Sans"]
                          },
                          "fontSize": {
                              "headline-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
                              "display-lg-mobile": ["40px", {"lineHeight": "48px", "letterSpacing": "-0.02em", "fontWeight": "800"}],
                              "display-lg": ["72px", {"lineHeight": "80px", "letterSpacing": "-0.04em", "fontWeight": "800"}],
                              "headline-md": ["32px", {"lineHeight": "40px", "fontWeight": "700"}],
                              "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
                              "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
                              "label-bold": ["14px", {"lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "600"}]
                          }
                      }
                  }
              }
            `
          }}
        />
        <style dangerouslySetInnerHTML={{ __html: `
          .material-symbols-outlined {
              font-variation-settings: 'FILL' 0, 'wght' 400, 'GRAD' 0, 'opsz' 24;
          }
        `}} />
      </head>
      <body className="bg-background text-on-background font-body-md antialiased selection:bg-primary-container selection:text-on-primary-container min-h-screen flex flex-col">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
